language: java
jdk:
  - openjdk8
branches:
  only:
    - master
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"
notifications:
  email:
    recipients:
      - khskeb0513@gmail.com

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../
  - mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/busanhs-spring1.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: busanhs-spring1
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: busanhs-spring1
    key: busanhs-spring1.zip
    bundle_type: zip
    application: busanhs-spring1
    deployment-group: busanhs-spring1-group
    region: ap-northeast-2
    wait-until-deploy: true